name: Build and deploy Python app to Azure Web App - Mercado-Versátil

on:
  push:
    branches:
      - teste
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r projeto_fds/requirements.txt

      - name: Cleaning testing files
        run: |
          cd projeto_fds/
          rm db.sqlite3
          rm .env
          cd ..

      - name: Zip artifact for deployment
        run: |
          cd projeto_fds/
          zip release.zip ./* -r
          cd ..
          mv projeto_fds/release.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EC21CC2B953B459B8AF2986CC011860D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F06367B836924CFE809330DCC7F19B4A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4E1C1F15E8CE42D796D787ED458126B8 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Mercado-Versátil'
